"""Prepare human recordings for deterministic recorded-strategy playback."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from .model import MacroEvent


@dataclass(slots=True, frozen=True)
class PreparationStats:
    original_events: int
    prepared_events: int
    removed_idle_mouse_moves: int
    removed_ability_key_events: int
    collapsed_repeated_key_down: int
    removed_orphan_key_up: int
    added_key_releases: int


def prepare_recorded_strategy(
    events: Iterable[MacroEvent],
    *,
    automatic_keys: set[str] | None = None,
) -> tuple[list[MacroEvent], PreparationStats]:
    """Remove recording noise while preserving clicks, scrolls, and camera drags.

    Mouse-button and scroll events already carry absolute coordinates, so free
    mouse movement between actions is unnecessary. Movement while any mouse
    button is held is retained because it can represent an intentional camera
    or interface drag.

    Keys controlled by automatic ability workers are removed from the recorded
    stream. Repeated ``key_down`` events generated by keyboard auto-repeat are
    collapsed and any missing releases are added at the end.
    """

    source = [MacroEvent(event.t, event.type, dict(event.data)) for event in events]
    pulse_keys = {value.casefold() for value in (automatic_keys or set())}
    prepared: list[MacroEvent] = []
    held_keys: set[tuple[str, str]] = set()
    held_buttons: set[str] = set()

    idle_moves = 0
    ability_events = 0
    repeated_down = 0
    orphan_up = 0

    for event in source:
        if event.type in {"key_down", "key_up"}:
            raw_key = event.data.get("key", {})
            kind = str(raw_key.get("kind", ""))
            value = str(raw_key.get("value", ""))
            token = (kind, value)

            if value.casefold() in pulse_keys:
                ability_events += 1
                continue

            if event.type == "key_down":
                if token in held_keys:
                    repeated_down += 1
                    continue
                held_keys.add(token)
            else:
                if token not in held_keys:
                    orphan_up += 1
                    continue
                held_keys.remove(token)

            prepared.append(event)
            continue

        if event.type == "mouse_button":
            button = str(event.data.get("button", "unknown"))
            if bool(event.data.get("pressed")):
                held_buttons.add(button)
            else:
                held_buttons.discard(button)
            prepared.append(event)
            continue

        if event.type == "mouse_move":
            if held_buttons:
                prepared.append(event)
            else:
                idle_moves += 1
            continue

        prepared.append(event)

    timestamp = source[-1].t if source else 0.0
    releases_added = 0
    for kind, value in sorted(held_keys):
        timestamp = round(timestamp + 0.01, 6)
        prepared.append(
            MacroEvent(
                timestamp,
                "key_up",
                {"key": {"kind": kind, "value": value}},
            )
        )
        releases_added += 1

    prepared.sort(key=lambda event: event.t)
    return prepared, PreparationStats(
        original_events=len(source),
        prepared_events=len(prepared),
        removed_idle_mouse_moves=idle_moves,
        removed_ability_key_events=ability_events,
        collapsed_repeated_key_down=repeated_down,
        removed_orphan_key_up=orphan_up,
        added_key_releases=releases_added,
    )
